name: pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Conda 
      uses: goanpeca/setup-miniconda@v1
      with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
    - name: Install package with dependencies
      run: |
        conda info
        python -m pip install --upgrade pip
        pip install .
        conda install -y lhapdf -c https://packages.nnpdf.science/conda
        conda install -y validphys -c https://packages.nnpdf.science/conda
    - name: Test modules and coverage with pytest
      run: |
        pip install .[tests]
        pytest -v tests/ --cov=./src/pycompressor
