# Test modules

name: pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Conda 
      uses: conda-incubator/setup-miniconda@v2
      with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
    - name: Install package with dependencies
      shell: bash --login {0}
      run: |
        conda info
        # Create .condarc file
        echo "channels: " >> ~/.condarc
        echo " - https://packages.nnpdf.science/private" >> ~/.condarc
        echo " - https://packages.nnpdf.science/public" >> ~/.condarc
        echo " - defaults" >> ~/.condarc
        echo " - conda-forge" >> ~/.condarc
        # Install nnpdf
        conda install -y nnpdf
        # Install package
        python -m pip install --upgrade pip
        pip install .
    - name: Test modules and coverage with pytest
      shell: bash --login {0}
      run: |
        pip install -r tests-requirements.txt
        pytest -v tests/ --cov=./src/pycompressor --cov-report=xml
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.PYCOMP_COV }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
